/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/Mock_city1_nohole.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const  Mock2 = (props) => {
  const { nodes, materials } = useGLTF('./models/Mock_city1_nohole.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface379_1.geometry} material={materials.standardSurface1} />
      <mesh geometry={nodes.polySurface379_2.geometry} material={materials.lambert4} />
      <mesh geometry={nodes.polySurface379_3.geometry} material={materials.lambert2} />
    </group>
  )
}

useGLTF.preload('./models/Mock_city1_nohole.glb')
export default Mock2;